package uz.yalla.sipphone.ui.strings

object RuStrings : StringResources {
    override val loginTitle = "Yalla SIP Phone"
    override val loginSubtitle = "Вход в систему"
    override val loginPasswordPlaceholder = "Введите пароль"
    override val loginButton = "Войти"
    override val loginConnecting = "Подключение..."
    override val loginRetry = "Повторить"
    override val loginManualConnection = "Ручное подключение"
    override val errorWrongPassword = "Неверный пароль"
    override val errorNetworkFailed = "Не удалось подключиться к серверу"
    override val agentStatusOnline = "На линии"
    override val agentStatusBusy = "Занят"
    override val agentStatusOffline = "Не на линии"
    override val sipConnected = "Подключен"
    override val sipReconnecting = "Подключение"
    override val sipDisconnected = "Отключен"
    override val sipDisconnectBlockedByCall = "Активный вызов, нельзя отключить"
    override val sipReconnectHint = "Нажмите → переподключить"
    override val sipRinging = "Звонок..."
    override val settingsTitle = "Настройки"
    override val settingsTheme = "Тема"
    override val settingsLocale = "Язык"
    override val settingsLogout = "Выход"
    override val settingsLogoutConfirm = "Вы хотите выйти из системы?"
    override val settingsLogoutConfirmTitle = "Выход"
    override val appTitle = "Yalla SIP Phone"
    override val buttonConnect = "Подключить"
    override val buttonCancel = "Отмена"
    override val labelServer = "Сервер"
    override val labelPort = "Порт"
    override val labelUsername = "Пользователь"
    override val labelPassword = "Пароль"
    override val placeholderServer = "sip.example.com"
    override val placeholderUsername = "1001"
    override val placeholderDispatcherUrl = "http://192.168.0.234:5173"
}
