package uz.yalla.sipphone.ui.strings

object UzStrings : StringResources {
    override val loginTitle = "Yalla SIP Phone"
    override val loginSubtitle = "Tizimga kirish"
    override val loginPasswordPlaceholder = "Parolni kiriting"
    override val loginButton = "Kirish"
    override val loginConnecting = "Ulanmoqda..."
    override val loginRetry = "Qayta urinish"
    override val loginManualConnection = "Qo'lda ulanish"
    override val errorWrongPassword = "Parol noto'g'ri"
    override val errorNetworkFailed = "Serverga ulanib bo'lmadi"
    override val agentStatusOnline = "Liniyada"
    override val agentStatusBusy = "Band"
    override val agentStatusOffline = "Liniyada emas"
    override val sipConnected = "Ulangan"
    override val sipReconnecting = "Ulanmoqda"
    override val sipDisconnected = "Uzilgan"
    override val sipDisconnectBlockedByCall = "Aktiv qo'ng'iroq bor, uzib bo'lmaydi"
    override val sipReconnectHint = "Bosing → qayta ulash"
    override val sipRinging = "Qo'ng'iroq..."
    override val buttonCall = "Qo'ng'iroq"
    override val buttonAnswer = "Javob berish"
    override val buttonReject = "Rad etish"
    override val buttonHangup = "Tugatish"
    override val buttonMute = "Ovozni o'chirish"
    override val buttonUnmute = "Ovozni yoqish"
    override val buttonHold = "Kutishga qo'yish"
    override val buttonResume = "Davom ettirish"
    override val placeholderPhone = "+998 __ ___ __ __"
    override val settingsTitle = "Sozlamalar"
    override val settingsTheme = "Mavzu"
    override val settingsLocale = "Til"
    override val settingsLogout = "Chiqish"
    override val settingsLogoutConfirm = "Tizimdan chiqmoqchimisiz?"
    override val settingsLogoutConfirmTitle = "Chiqish"
    override val appTitle = "Yalla SIP Phone"
    override val buttonConnect = "Ulanish"
    override val buttonCancel = "Bekor qilish"
    override val labelServer = "Server"
    override val labelPort = "Port"
    override val labelUsername = "Foydalanuvchi"
    override val labelPassword = "Parol"
    override val placeholderServer = "sip.example.com"
    override val placeholderUsername = "1001"
    override val placeholderDispatcherUrl = "http://192.168.0.234:5173"
}
